### ISSUE TITLE
Lots of error!

### ISSUE THREAD

**Issue by armagadon159753** [ChaostixZix/SkyBlock#1]
![screenshot_2017-06-04-20-42-37](https://cloud.githubusercontent.com/assets/25569806/26764399/87c53a08-4966-11e7-9d1e-04c45fa10e6c.png)

**Comment by ChaostixZix** [comment]
we'll fix it

**Comment by armagadon159753** [comment]
You plugin working on PmmP, Bluelight, or Tesseract?
